# Generated by Django 4.1.1 on 2022-12-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supermegasite', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('card_number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.CharField(choices=[('ACCEPTED', 'ПРИНЯТ'), ('IN_PROCESSING', 'В ОБРАБОТКЕ'), ('SENT', 'ОТПРАВЛЕН'), ('RECEIVED', 'ПОЛУЧЕН')], default='ПРИНЯТ', max_length=55, verbose_name='Статус заказа')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='supermegasite.product')),
            ],
        ),
    ]
